[features]
seeds = false
skip-lint = false
[programs.localnet]
slcalculatordapp = "721Nyj83Zm47fcmPwJXLBC5bvGiDYxCdNCLmgMmLec5E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/moonman369/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
